from importlib.metadata import PackageNotFoundError, version

from ipor_fusion.core.context import Web3Context
from ipor_fusion.core.plasma_vault import PlasmaVault, BalanceFuse
from ipor_fusion.core.access import AccessManager, RoleAccount, RoleStatus
from ipor_fusion.core.rewards_manager import RewardsManager, VestingData
from ipor_fusion.core.erc20 import ERC20
from ipor_fusion.core.withdraw_manager import (
    WithdrawManager,
    WithdrawRequestInfo,
    PendingRequestsInfo,
)
from ipor_fusion.core.oracle import PriceOracleMiddleware, AssetPriceSource
from ipor_fusion.readers import (
    MorphoReader,
    MorphoMarket,
    MorphoPosition,
    MorphoMarketParams,
    AaveV3Reader,
    AaveV3UserAccountData,
    CompoundV3Reader,
    LendingMarketHealth,
    VaultLendingHealth,
    fetch_vault_lending_health,
    UniswapV3Reader,
    UniswapV3Position,
    RamsesV2Reader,
    RamsesV2Position,
)
from ipor_fusion.fuses import (
    FuseAction,
    Fuse,
    StakeFuse,
    AaveV3SupplyFuse,
    AaveV3BorrowFuse,
    MorphoSupplyFuse,
    MorphoCollateralFuse,
    MorphoBorrowFuse,
    MorphoFlashLoanFuse,
    MorphoClaimFuse,
    UniswapV3SwapFuse,
    UniswapV3NewPositionFuse,
    UniswapV3ModifyPositionFuse,
    UniswapV3CollectFuse,
    UniswapV3NewPositionEvent,
    UniswapV3ClosePositionEvent,
    UniswapV3Events,
    CompoundV3SupplyFuse,
    RamsesV2NewPositionFuse,
    RamsesV2ModifyPositionFuse,
    RamsesV2CollectFuse,
    RamsesClaimFuse,
    RamsesNewPositionEvent,
    RamsesEvents,
    GearboxSupplyFuse,
    GearboxStakeFuse,
    ERC4626SupplyFuse,
    UniversalTokenSwapperFuse,
    FluidInstadappSupplyFuse,
    FluidInstadappStakingFuse,
)
from ipor_fusion.config.roles import Roles
from ipor_fusion.market_ids import IporFusionMarkets
from ipor_fusion.errors import (
    IporFusionError,
    TransactionError,
)
from ipor_fusion.types import (
    Amount,
    Shares,
    Decimals,
    MarketId,
    TokenId,
    Fee,
    Tick,
    Liquidity,
    RoleId,
    ChainId,
    MorphoBlueMarketId,
    Price,
    Period,
    MAX_UINT256,
)

try:
    __version__ = version("ipor_fusion")
except PackageNotFoundError:
    __version__ = "0.0.0"

__all__ = [
    "__version__",
    "Web3Context",
    "PlasmaVault",
    "AccessManager",
    "RoleAccount",
    "RoleStatus",
    "RewardsManager",
    "VestingData",
    "ERC20",
    "WithdrawManager",
    "WithdrawRequestInfo",
    "PendingRequestsInfo",
    "BalanceFuse",
    "PriceOracleMiddleware",
    "AssetPriceSource",
    "FuseAction",
    "Fuse",
    "StakeFuse",
    "AaveV3SupplyFuse",
    "AaveV3BorrowFuse",
    "MorphoSupplyFuse",
    "MorphoCollateralFuse",
    "MorphoBorrowFuse",
    "MorphoFlashLoanFuse",
    "MorphoClaimFuse",
    "UniswapV3SwapFuse",
    "UniswapV3NewPositionFuse",
    "UniswapV3ModifyPositionFuse",
    "UniswapV3CollectFuse",
    "UniswapV3NewPositionEvent",
    "UniswapV3ClosePositionEvent",
    "UniswapV3Events",
    "CompoundV3SupplyFuse",
    "RamsesV2NewPositionFuse",
    "RamsesV2ModifyPositionFuse",
    "RamsesV2CollectFuse",
    "RamsesClaimFuse",
    "RamsesNewPositionEvent",
    "RamsesEvents",
    "GearboxSupplyFuse",
    "GearboxStakeFuse",
    "ERC4626SupplyFuse",
    "UniversalTokenSwapperFuse",
    "FluidInstadappSupplyFuse",
    "FluidInstadappStakingFuse",
    "Roles",
    "IporFusionMarkets",
    "IporFusionError",
    "TransactionError",
    "Amount",
    "Shares",
    "Decimals",
    "MarketId",
    "TokenId",
    "Fee",
    "Tick",
    "Liquidity",
    "RoleId",
    "ChainId",
    "MorphoBlueMarketId",
    "Price",
    "Period",
    "MAX_UINT256",
    "MorphoReader",
    "MorphoMarket",
    "MorphoPosition",
    "MorphoMarketParams",
    "AaveV3Reader",
    "AaveV3UserAccountData",
    "CompoundV3Reader",
    "LendingMarketHealth",
    "VaultLendingHealth",
    "fetch_vault_lending_health",
    "UniswapV3Reader",
    "UniswapV3Position",
    "RamsesV2Reader",
    "RamsesV2Position",
]
