name: Python build

on:
  workflow_call:

    secrets:
      ARBITRUM_PROVIDER_URL:
        required: true
      BASE_PROVIDER_URL:
        required: true
      ETHEREUM_PROVIDER_URL:
        required: true

    inputs:
      python-version:
        description: "Python version"
        type: string
        default: 3.12
        required: false
      test-options:
        description: "Extra pytest options"
        type: string
        default: "-v -s"
        required: false
      format-code-enabled:
        description: "Enable code formatting"
        type: boolean
        default: true
        required: false
      static-code-analysis-enabled:
        description: "Enable static code analysis"
        type: boolean
        default: true
        required: false
      build-enabled:
        description: "Enable package build"
        type: boolean
        default: true
        required: false
      test-enabled:
        description: "Enable pytest tests"
        type: boolean
        default: true
        required: false

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # from tag: v6.0.3
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          submodules: recursive

      - name: Set up uv
        # from tag: v5.4.2
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86
        with:
          python-version: ${{ inputs.python-version }}
          enable-cache: true

      - name: Install
        run: uv sync --all-extras --frozen
        id: install

      - name: Format code
        if: inputs.format-code-enabled
        run: uv run black --check ./
        id: format-code

      - name: Static code analysis
        if: inputs.static-code-analysis-enabled
        run: uv run pylint --rcfile=pylintrc.toml --verbose --recursive=y .
        id: static-code-analyze

      - name: Type check
        if: inputs.static-code-analysis-enabled
        run: uv run mypy .
        id: type-check

      - name: Build
        if: inputs.build-enabled
        run: uv build
        id: build

      - name: Tests
        if: inputs.test-enabled
        run: |
          uv run pytest ${{ inputs.test-options }}
        env:
          ETHEREUM_PROVIDER_URL: ${{ secrets.ETHEREUM_PROVIDER_URL }}
          ARBITRUM_PROVIDER_URL: ${{ secrets.ARBITRUM_PROVIDER_URL }}
          BASE_PROVIDER_URL: ${{ secrets.BASE_PROVIDER_URL }}
        id: tests

      - name: Coverage summary
        if: inputs.test-enabled && always() && steps.tests.outcome != 'skipped'
        run: |
          uv run coverage report --format=markdown >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage artifact
        if: inputs.test-enabled && always() && steps.tests.outcome != 'skipped'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

